def create_tables(conn):
    cursor = conn.cursor()
    
    covid_table_query = '''CREATE TABLE IF NOT EXISTS covid_data (
        id SERIAL PRIMARY KEY,
        iso_code VARCHAR(10) NOT NULL,
        continent VARCHAR(50),
        location VARCHAR(100) NOT NULL,
        date DATE NOT NULL,
        total_cases BIGINT,
        new_cases BIGINT,
        new_cases_smoothed BIGINT,
        total_deaths BIGINT,
        new_deaths BIGINT,
        new_deaths_smoothed BIGINT,
        total_cases_per_million DECIMAL(15, 2),
        new_cases_per_million DECIMAL(15, 2),
        new_cases_smoothed_per_million DECIMAL(15, 2),
        total_deaths_per_million DECIMAL(15, 2),
        new_deaths_per_million DECIMAL(15, 2),
        new_deaths_smoothed_per_million DECIMAL(15, 2),
        reproduction_rate DECIMAL(10, 2),
        icu_patients BIGINT,
        icu_patients_per_million DECIMAL(15, 2),
        hosp_patients BIGINT,
        hosp_patients_per_million DECIMAL(15, 2),
        weekly_icu_admissions BIGINT,
        weekly_icu_admissions_per_million DECIMAL(15, 2),
        weekly_hosp_admissions BIGINT,
        weekly_hosp_admissions_per_million DECIMAL(15, 2),
        new_tests BIGINT,
        total_tests BIGINT,
        total_tests_per_thousand DECIMAL(15, 2),
        new_tests_per_thousand DECIMAL(15, 2),
        new_tests_smoothed BIGINT,
        new_tests_smoothed_per_thousand BIGINT,
        positive_rate DECIMAL(10, 2),
        tests_per_case DECIMAL(15, 2),
        tests_units VARCHAR(50),
        total_vaccinations BIGINT,
        people_vaccinated BIGINT,
        people_fully_vaccinated BIGINT,
        new_vaccinations BIGINT,
        new_vaccinations_smoothed BIGINT,
        total_vaccinations_per_hundred DECIMAL(15, 2),
        people_vaccinated_per_hundred DECIMAL(15, 2),
        people_fully_vaccinated_per_hundred DECIMAL(15, 2),
        new_vaccinations_smoothed_per_million BIGINT,
        stringency_index DECIMAL(10, 2),
        population BIGINT,
        population_density DECIMAL(15, 2),
        median_age DECIMAL(10, 2),
        aged_65_older DECIMAL(10, 2),
        aged_70_older DECIMAL(10, 2),
        gdp_per_capita DECIMAL(15, 2),
        extreme_poverty DECIMAL(10, 2),
        cardiovasc_death_rate DECIMAL(10, 2),
        diabetes_prevalence DECIMAL(10, 2),
        female_smokers DECIMAL(10, 2),
        male_smokers DECIMAL(10, 2),
        handwashing_facilities DECIMAL(10, 2),
        hospital_beds_per_thousand DECIMAL(10, 2),
        life_expectancy DECIMAL(10, 2),
        human_development_index DECIMAL(10, 2)
    );
    '''

    
    cursor.execute(covid_table_query)
    
    vaccin_table_query = '''CREATE TABLE IF NOT EXISTS vaccin_data (
        id SERIAL PRIMARY KEY,
        iso_code VARCHAR(10) NOT NULL,
        continent VARCHAR(50),
        location VARCHAR(100) NOT NULL,
        date DATE NOT NULL,
        new_tests BIGINT,
        total_tests BIGINT,
        total_tests_per_thousand DECIMAL(15, 2),
        new_tests_per_thousand DECIMAL(15, 2),
        new_tests_smoothed BIGINT,
        new_tests_smoothed_per_thousand BIGINT,
        positive_rate DECIMAL(10, 4),
        tests_per_case DECIMAL(15, 2),
        tests_units VARCHAR(50),
        total_vaccinations BIGINT,
        people_vaccinated BIGINT,
        people_fully_vaccinated BIGINT,
        new_vaccinations BIGINT,
        new_vaccinations_smoothed BIGINT,
        total_vaccinations_per_hundred DECIMAL(15, 2),
        people_vaccinated_per_hundred DECIMAL(15, 2),
        people_fully_vaccinated_per_hundred DECIMAL(15, 2),
        new_vaccinations_smoothed_per_million BIGINT,
        stringency_index DECIMAL(10, 2),
        population_density DECIMAL(15, 2),
        median_age DECIMAL(10, 2),
        aged_65_older DECIMAL(10, 2),
        aged_70_older DECIMAL(10, 2),
        gdp_per_capita DECIMAL(15, 2),
        extreme_poverty DECIMAL(10, 2),
        cardiovasc_death_rate DECIMAL(10, 2),
        diabetes_prevalence DECIMAL(10, 2),
        female_smokers DECIMAL(10, 2),
        male_smokers DECIMAL(10, 2),
        handwashing_facilities DECIMAL(10, 2),
        hospital_beds_per_thousand DECIMAL(10, 2),
        life_expectancy DECIMAL(10, 2),
        human_development_index DECIMAL(10, 2)
    );
    '''
    
    cursor.execute(vaccin_table_query)
    conn.commit()
    cursor.close()
